FROM node:22-alpine

RUN apk add --no-cache \
  build-base \
  python3 \
  autoconf \
  automake \
  zlib-dev \
  libpng-dev \
  vips-dev \
  git

WORKDIR /opt/app

COPY package/package.json package/package-lock.json ./

ENV NODE_ENV=production

RUN npm config set fetch-retry-maxtimeout 600000 -g \
 && npm ci --omit=dev

ENV PATH=/opt/app/node_modules/.bin:$PATH
