FROM node:22-alpine

RUN apk add --no-cache \
    build-base \
    gcc \
    autoconf \
    automake \
    zlib-dev \
    libpng-dev \
    nasm \
    bash \
    vips-dev \
    git

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt

COPY package.json package-lock.json ./

RUN npm install -g node-gyp \
 && npm config set fetch-retry-maxtimeout 600000 -g \
 && npm ci

ENV PATH=/opt/node_modules/.bin:$PATH

COPY docker-entrypoint.develop.sh /opt/docker-entrypoint.sh
RUN chmod +x /opt/docker-entrypoint.sh

WORKDIR /opt/app

EXPOSE 1337

ENTRYPOINT ["/opt/docker-entrypoint.sh"]
CMD ["npm", "run", "develop"]
